language: rust
env:
  global:
    - PROJECT_NAME: cucumber-messages
    - RUST_BACKTRACE: full
rust:
  # Minimum Rust supported channel to make sure the project continues to work on the advertised minimum version.
  - 1.40.0
  - beta
  - nightly
matrix:
  fast_finish: true
